/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/artifacts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Upload */
    post: operations['upload_v1_artifacts_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/artifacts/signals': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Upload Signals */
    post: operations['upload_signals_v1_artifacts_signals_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/artifacts/{artifact_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Artifact */
    get: operations['artifact_v1_artifacts__artifact_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/artifacts/{artifact_id}/preview': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Preview */
    get: operations['preview_v1_artifacts__artifact_id__preview_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/future/jobs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Future Job */
    post: operations['future_job_v1_future_jobs_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/future/plan': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Future Plan */
    post: operations['future_plan_v1_future_plan_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/geocode': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Geocode */
    post: operations['geocode_v1_geocode_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/jobs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Jobs */
    get: operations['list_jobs_v1_jobs_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/jobs/{job_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Job */
    get: operations['job_v1_jobs__job_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/jobs/{job_id}/artifacts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Artifacts */
    get: operations['artifacts_v1_jobs__job_id__artifacts_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/jobs/{job_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Cancel */
    post: operations['cancel_v1_jobs__job_id__cancel_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/weather/discover': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Discover */
    post: operations['discover_v1_weather_discover_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/weather/jobs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Weather Job */
    post: operations['weather_job_v1_weather_jobs_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/weather/plan': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Plan */
    post: operations['plan_v1_weather_plan_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** ArtifactBundle */
    ArtifactBundle: {
      /** Additional */
      additional?: components['schemas']['ArtifactRef'][]
      /** Bundle Id */
      bundle_id: string
      /** Issues */
      issues?: components['schemas']['Issue'][]
      manifest: components['schemas']['ArtifactRef']
      plan: components['schemas']['ArtifactRef']
      qc: components['schemas']['ArtifactRef']
      request: components['schemas']['ArtifactRef']
      /** Weather */
      weather?: components['schemas']['ArtifactRef'][]
    }
    /** ArtifactRef */
    ArtifactRef: {
      /** Bytes */
      bytes: number
      /** Id */
      id: string
      /** Media Type */
      media_type: string
      /** Path */
      path: string
      /** Role */
      role: string
      /** Sha256 */
      sha256: string
    }
    /** Body_upload_v1_artifacts_post */
    Body_upload_v1_artifacts_post: {
      /** File */
      file: string
    }
    /** BoundingBox */
    BoundingBox: {
      /** East */
      east: number
      /** North */
      north: number
      /** South */
      south: number
      /** West */
      west: number
    }
    /** Candidate */
    Candidate: {
      /** Available Years */
      available_years?: number[]
      /** Id */
      id: string
      /** Interval Minutes */
      interval_minutes?: number | null
      /** Location Id */
      location_id?: string | null
      /** Missing Fields */
      missing_fields?: string[]
      /** Observed At */
      observed_at?: string
      /** Product Id */
      product_id?: string | null
      /** Requires Credentials */
      requires_credentials?: string[]
      /** Selection Reasons */
      selection_reasons?: string[]
      source: components['schemas']['SourceRef']
      /** Variables */
      variables?: string[]
      /** Warnings */
      warnings?: string[]
      /** Weather Types */
      weather_types?: string[]
    }
    /** DiscoveryResult */
    DiscoveryResult: {
      /** Candidates */
      candidates: components['schemas']['Candidate'][]
      /** Issues */
      issues?: components['schemas']['Issue'][]
      /** Locations */
      locations: components['schemas']['Location'][]
      /** Observed At */
      observed_at?: string
      /** Selected Candidate Ids */
      selected_candidate_ids?: string[]
    }
    /** ErrorResponse */
    ErrorResponse: {
      /** Code */
      code?: string | null
      /** Detail */
      detail?: string | null
      /** Fields */
      fields?: (string | number)[][] | null
      /** Message */
      message?: string | null
      /** Retryable */
      retryable?: boolean | null
      /** Severity */
      severity?: string | null
    }
    /** FetchTask */
    FetchTask: {
      /** Cache Key */
      cache_key: string
      /** Dependents */
      dependents?: string[]
      /** Id */
      id: string
      /** Parameters */
      parameters: {
        [key: string]: unknown
      }
      source: components['schemas']['SourceRef']
    }
    /** FutureRequest */
    FutureRequest: {
      /** Baseline */
      baseline: string
      /** Climate Period */
      climate_period?: [number, number] | null
      /**
       * Climate Scenario
       * @enum {string}
       */
      climate_scenario: 'ssp126' | 'ssp245' | 'ssp370' | 'ssp585' | 'rcp45' | 'rcp85'
      /** Extreme */
      extreme?: {
        [key: string]: string | number
      }
      /** Members */
      members?: string[]
      /**
       * Method
       * @default morph
       * @enum {string}
       */
      method: 'morph' | 'climate_profile'
      /** Models */
      models?: string[]
      /**
       * Profile
       * @default typical
       * @enum {string}
       */
      profile: 'typical' | 'extreme' | 'ensemble' | 'sampled'
      /** Reference Period */
      reference_period?: [number, number] | null
      /**
       * Schema Version
       * @default 0.1
       * @constant
       */
      schema_version: '0.1'
      /** Signals */
      signals?: string | null
      /** Target Year */
      target_year?: number | null
    }
    /** GeocodeQuery */
    GeocodeQuery: {
      /**
       * Mode
       * @default point
       */
      mode: string
      /** Query */
      query: string
    }
    /** GeocodeResult */
    GeocodeResult: {
      /**
       * Attribution
       * @default Open-Meteo / GeoNames
       */
      attribution: string
      /** Candidates */
      candidates: components['schemas']['Location'][]
      /** Issues */
      issues?: components['schemas']['Issue'][]
      /**
       * Mode
       * @default point
       */
      mode: string
      /** Query */
      query: string
    }
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string
      /** Version */
      version: string
    }
    /** HybridPolicy */
    HybridPolicy: {
      /** Assignments */
      assignments?: {
        [key: string]: string
      }
      /**
       * Enabled
       * @default false
       */
      enabled: boolean
    }
    /** Issue */
    Issue: {
      /** Code */
      code: string
      /** Field */
      field?: string | null
      /** Location Id */
      location_id?: string | null
      /** Message */
      message: string
      /**
       * Retryable
       * @default false
       */
      retryable: boolean
      /**
       * Severity
       * @default warning
       * @enum {string}
       */
      severity: 'info' | 'warning' | 'error'
      /** Task Id */
      task_id?: string | null
    }
    /** JobListResponse */
    JobListResponse: {
      /** Items */
      items: components['schemas']['WeatherJob'][]
      /** Next Cursor */
      next_cursor?: string | null
    }
    /** JobSubmission */
    JobSubmission: {
      /** Idempotency Key */
      idempotency_key?: string | null
      plan: components['schemas']['WeatherPlan']
    }
    /** Location */
    Location: {
      /** Elevation */
      elevation?: number | null
      /** Id */
      id?: string | null
      /** Lat */
      lat: number
      /** Lon */
      lon: number
      /** Name */
      name?: string | null
      /**
       * Standard Offset Minutes
       * @default 0
       */
      standard_offset_minutes: number
    }
    /** MonthlySignal */
    MonthlySignal: {
      /**
       * Calendar
       * @default gregorian
       */
      calendar: string
      /** Climate Period */
      climate_period: [number, number]
      /** Dtr Delta */
      dtr_delta?: number[]
      /** Humidity Delta */
      humidity_delta?: number[]
      /** License */
      license: string
      /** License Registry */
      license_registry?: {
        [key: string]: string
      }
      /** Member */
      member: string
      /** Model */
      model: string
      /** Original Licenses */
      original_licenses?: string[]
      /** Pressure Delta */
      pressure_delta?: number[]
      /** Profile Year */
      profile_year?: number | null
      /** Reference Period */
      reference_period: [number, number]
      /** Scenario */
      scenario: string
      /** Solar Ratio */
      solar_ratio?: number[]
      /** Source Checksums */
      source_checksums: string[]
      /** Source Location */
      source_location?: {
        [key: string]: number
      }
      /** Source Uri */
      source_uri: string
      /** Temperature Delta */
      temperature_delta: number[]
      /** Units */
      units?: {
        [key: string]: string
      }
      /** Warnings */
      warnings?: string[]
      /** Wind Ratio */
      wind_ratio?: number[]
    }
    /** MonthlySummary */
    MonthlySummary: {
      /** Expected */
      expected: number
      /** Month */
      month: number
      /** Values */
      values: {
        [key: string]: components['schemas']['SummaryValue']
      }
      /** Year */
      year: number
    }
    /** OutputSpec */
    OutputSpec: {
      /** Name */
      name: string
      /** Requested Location Id */
      requested_location_id: string
      /** Task Ids */
      task_ids: string[]
    }
    /** PolygonQuery */
    PolygonQuery: {
      /** Coordinates */
      coordinates: [number, number][][]
      /**
       * Type
       * @default Polygon
       * @constant
       */
      type: 'Polygon'
    }
    /** PreviewRow */
    PreviewRow: {
      /** Timestamp */
      timestamp: string
      /** Values */
      values: {
        [key: string]: number | null
      }
    }
    /** SamplingSpec */
    SamplingSpec: {
      /**
       * Dx Km
       * @default 25
       */
      dx_km: number
      /**
       * Dy Km
       * @default 25
       */
      dy_km: number
      /**
       * Max Locations
       * @default 1000
       */
      max_locations: number
      /**
       * Offset X Km
       * @default 0
       */
      offset_x_km: number
      /**
       * Offset Y Km
       * @default 0
       */
      offset_y_km: number
    }
    /** SourceRef */
    SourceRef: {
      /**
       * Access Path
       * @default https
       */
      access_path: string
      /** Citation */
      citation?: string | null
      /** Dataset */
      dataset: string
      /** Identity */
      identity?: string | null
      /** License */
      license?: string | null
      location?: components['schemas']['Location'] | null
      /** Provider */
      provider: string
      /**
       * Provisional
       * @default true
       */
      provisional: boolean
      /** Resolution Km */
      resolution_km?: number | null
      /** Version */
      version?: string | null
    }
    /** SummaryValue */
    SummaryValue: {
      /** Maximum */
      maximum?: number | null
      /** Mean */
      mean?: number | null
      /** Minimum */
      minimum?: number | null
      /** Sum */
      sum?: number | null
      /** Valid */
      valid: number
    }
    /** TransformStep */
    TransformStep: {
      /** Id */
      id: string
      /** Inputs */
      inputs?: string[]
      /** Method */
      method: string
      /** Parameters */
      parameters?: {
        [key: string]: unknown
      }
      /**
       * Version
       * @default 0.1
       */
      version: string
    }
    /** WeatherJob */
    WeatherJob: {
      bundle?: components['schemas']['ArtifactBundle'] | null
      /**
       * Cancellation Requested
       * @default false
       */
      cancellation_requested: boolean
      /**
       * Completed
       * @default 0
       */
      completed: number
      /** Errors */
      errors?: components['schemas']['Issue'][]
      /**
       * Failed
       * @default 0
       */
      failed: number
      /** Finished At */
      finished_at?: string | null
      /** Id */
      id: string
      /** Idempotency Key */
      idempotency_key?: string | null
      /** Plan Hash */
      plan_hash: string
      /**
       * State
       * @default queued
       * @enum {string}
       */
      state: 'queued' | 'running' | 'completed' | 'partially_completed' | 'failed' | 'cancelled'
      /** Submitted At */
      submitted_at?: string
      /** Total */
      total: number
    }
    /** WeatherPlan */
    WeatherPlan: {
      /**
       * Capability Version
       * @default 0.1
       * @constant
       */
      capability_version: '0.1'
      /** Estimated Bytes */
      estimated_bytes?: number | null
      /**
       * Estimated Calls
       * @default 0
       */
      estimated_calls: number
      /**
       * Kind
       * @default weather
       * @enum {string}
       */
      kind: 'weather' | 'future'
      /** Outputs */
      outputs?: components['schemas']['OutputSpec'][]
      /**
       * Plan Hash
       * @default
       */
      plan_hash: string
      /** Request */
      request: components['schemas']['WeatherRequest'] | components['schemas']['FutureRequest']
      /**
       * Schema Version
       * @default 0.1
       * @constant
       */
      schema_version: '0.1'
      /** Selected Candidates */
      selected_candidates?: components['schemas']['Candidate'][]
      /** Tasks */
      tasks?: components['schemas']['FetchTask'][]
      /** Transforms */
      transforms?: components['schemas']['TransformStep'][]
      /** Warnings */
      warnings?: string[]
    }
    /** WeatherPreview */
    WeatherPreview: {
      /** Calendar */
      calendar: string
      location: components['schemas']['Location']
      /** Monthly */
      monthly: components['schemas']['MonthlySummary'][]
      /** Rows */
      rows: components['schemas']['PreviewRow'][]
      /**
       * Simulation Ready
       * @default false
       */
      simulation_ready: boolean
      /** Source Years */
      source_years: number[]
      /** Start */
      start: number
      /** Total Rows */
      total_rows: number
      /** Units */
      units: {
        [key: string]: string
      }
      /** Warnings */
      warnings?: string[]
    }
    /** WeatherRequest */
    WeatherRequest: {
      /** Dataset */
      dataset?: string | null
      /** End */
      end?: string | null
      /** Formats */
      formats?: 'epw'[]
      hybrid_policy?: components['schemas']['HybridPolicy']
      /**
       * Leap Policy
       * @default preserve
       * @constant
       */
      leap_policy: 'preserve'
      /** Locations */
      locations:
        | components['schemas']['Location'][]
        | components['schemas']['Location']
        | components['schemas']['BoundingBox']
        | components['schemas']['PolygonQuery']
      /**
       * Missing Policy
       * @default warn
       * @enum {string}
       */
      missing_policy: 'warn' | 'error'
      /**
       * Product
       * @default historical
       * @enum {string}
       */
      product: 'historical' | 'amy' | 'tmy' | 'tmyx' | 'published'
      /** Product Id */
      product_id?: string | null
      /** Providers */
      providers?: string[]
      /** Required Variables */
      required_variables?: string[]
      sampling?: components['schemas']['SamplingSpec']
      /**
       * Schema Version
       * @default 0.1
       * @constant
       */
      schema_version: '0.1'
      /** Start */
      start?: string | null
      /** Years */
      years?: number[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_health_get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  upload_v1_artifacts_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_v1_artifacts_post']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ArtifactRef']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  upload_signals_v1_artifacts_signals_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MonthlySignal'][]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ArtifactRef']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  artifact_v1_artifacts__artifact_id__get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        artifact_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  preview_v1_artifacts__artifact_id__preview_get: {
    parameters: {
      query?: {
        start?: number
        limit?: number
        variables?: string[] | null
      }
      header?: {
        authorization?: string | null
      }
      path: {
        artifact_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WeatherPreview']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  future_job_v1_future_jobs_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['JobSubmission']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WeatherJob']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  future_plan_v1_future_plan_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FutureRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WeatherPlan']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  geocode_v1_geocode_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GeocodeQuery']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GeocodeResult']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  list_jobs_v1_jobs_get: {
    parameters: {
      query?: {
        limit?: number
        cursor?: string | null
      }
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['JobListResponse']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  job_v1_jobs__job_id__get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WeatherJob']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  artifacts_v1_jobs__job_id__artifacts_get: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ArtifactBundle'] | null
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  cancel_v1_jobs__job_id__cancel_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path: {
        job_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WeatherJob']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  discover_v1_weather_discover_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WeatherRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DiscoveryResult']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  weather_job_v1_weather_jobs_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['JobSubmission']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WeatherJob']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  plan_v1_weather_plan_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WeatherRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WeatherPlan']
        }
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Content Too Large */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
