"""EnergyPlus EPW numeric columns, units and exact missing sentinels."""

FIELDS = [
    ("dry_bulb", 99.9),
    ("dew_point", 99.9),
    ("relative_humidity", 999),
    ("pressure", 999999),
    ("extraterrestrial_horizontal", 9999),
    ("extraterrestrial_direct", 9999),
    ("horizontal_infrared", 9999),
    ("ghi", 9999),
    ("dni", 9999),
    ("dhi", 9999),
    ("global_illuminance", 999999),
    ("direct_illuminance", 999999),
    ("diffuse_illuminance", 999999),
    ("zenith_luminance", 9999),
    ("wind_direction", 999),
    ("wind_speed", 999),
    ("total_sky_cover", 99),
    ("opaque_sky_cover", 99),
    ("visibility", 9999),
    ("ceiling_height", 99999),
    ("present_weather_observation", 9),
    ("present_weather_codes", 999999999),
    ("precipitable_water", 999),
    ("aerosol_optical_depth", 0.999),
    ("snow_depth", 999),
    ("days_since_snow", 99),
    ("albedo", 999),
    ("liquid_precipitation", 999),
    ("liquid_precipitation_quantity", 99),
]
HEADER_NAMES = [
    "LOCATION",
    "DESIGN CONDITIONS",
    "TYPICAL/EXTREME PERIODS",
    "GROUND TEMPERATURES",
    "HOLIDAYS/DAYLIGHT SAVINGS",
    "COMMENTS 1",
    "COMMENTS 2",
    "DATA PERIODS",
]
